--- 
title: "Kent R training"
author: "Lazaros Gonidis"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a work in progress"
---

# Prelude

## A few words...

...regarding the structure of this course. Given that this course is tailored mainly for psychologists we will not be discussing statistical concepts in great detail but instead we will be focusing on the R programming required to carry out different analyses. We will however, discussing assumptions where relevant as will help build a structure for our analysis.  

## A comment on the book structure

**The first six chapters will be covered mainly in Day 1 of the training event. From the seventh chapter (session) onwards we are focusing on Day 2 of the training.**

1. We will first start by introducing R and RStudio together and I will frequently be saying just "R" or just "RStudio" but in reality I will be implying **"using RStudio to carry out R commands"**.  

2. Once you are introduced to R and RStudio we will then move to get familiarised to **variables**, **vectors**, **matrices**, **dataframes**, **operations**, and **calculations**. Many argue that you cannot teach the use of R without teaching programming. I disagree, and we will be doing very minimal, almost no programming at all.  

3. This is thanks to **packages** and **functions** that will be doing the heavy lifting for us. We will therefore learn how to install and use additional packages and benefit from their *supply* of **functions**.

4. For example today we will be doing lots of work with data. This is because most of our work involves data preparation before we even carry out any analysis. We will therefore be manipulating data using a famous package collection called **tidyverse** and most specifically **dplyr** and **tidyr** (among others). It is through this work that you will become more confident and warm up to R.  

5. Once we are happy with how our data files look, we will proceed to data visualisations using another powerful package called **ggppubr**. **ggpubr** relies on **ggplot2** but it is simpler to use as it was built with graphs for publications in mind.  

6. Finally, we will *open the floor* to more practice examples and questions for you. You can even try today's techniques to some of your own data files and ask me questions in the process. This will conclude the first session and prepare us for the next session where we will be carrying out different types of analysis.
